#!/bin/bash

set -euo pipefail

# Check if OpenROAD executable exists in /usr/bin
if [ ! -f /usr/bin/openroad ]; then
    response=$(curl -s "https://api.github.com/repos/xplanlab/OpenROAD/releases/latest")
    latest_version=$(echo $response | grep -o '"tag_name": "[^"]*' | cut -d'"' -f4 || true)

    if [ -z "$latest_version" ]; then
        echo "Failed to get latest version from GitHub."
        echo "Reason: $response"

        echo "Trying to find the existing executable..."
        latest_version=$(ls -t openroad_* | head -n1 | cut -d'_' -f2 || true)

        if [ -z "$latest_version" ]; then
            echo "Failed to find the existing executable."
            exit 1
        fi
    fi

    file_name="openroad_$latest_version"

    if [ ! -f $file_name ]; then
        echo "Downloading executable $latest_version ..."
        curl -L https://github.com/xplanlab/OpenROAD/releases/latest/download/openroad -o "$file_name"
    fi

    cp $file_name /usr/bin/openroad
    chmod +x /usr/bin/openroad
fi

bash_mode=false

# Parse command arguments
while [ "$#" -gt 0 ]; do
    case "${1}" in
        -b|--bash)
            bash_mode=true
            ;;
        *)
            echo "unknown option: ${1}" >&2
            ;;
    esac
    shift 1
done

# Determine which mode to run
if [[ $bash_mode == "true" ]]; then
  exec /bin/bash
else
  python3 -m uvicorn api_server.main:app --host 0.0.0.0 --port 8080 --reload
fi
