from xroute_env.envs.ordering_training_env import OrderingTrainingEnv
from xroute_env.envs.ordering_evaluation_env import OrderingEvaluationEnv
from xroute_env.envs.static_region_env import StaticRegionEnv
